# Generated by Django 2.2.7 on 2020-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='key',
        ),
        migrations.AddField(
            model_name='key',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='verbose_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
